#!/usr/bin/env bash
FILENAME=${1?Error: no filename given}
echo "==========================================================="
echo "Creating page $FILENAME ..."
echo "==========================================================="
mkdir ./pages/page-$FILENAME
mkdir ./pages/page-$FILENAME/client
mkdir ./pages/page-$FILENAME/server
cp ./private/page-template/page.html.tmpl ./pages/page-$FILENAME/client/page-$FILENAME.html
cp ./private/page-template/page.less.tmpl ./pages/page-$FILENAME/client/page-$FILENAME.less
cp ./private/page-template/page-publications.js ./pages/page-$FILENAME/server/page-publications.js
cp ./private/page-template/page.js.tmpl ./pages/page-$FILENAME/page-$FILENAME.js
echo "PAGE CREATED! Don't forget to search-and-replace:"
echo "Replace FILE_NAME_GOES_HERE with file name"
echo "Replace TEMPLATE_NAME_GOES_HERE with camel-cased filename"
echo "==========================================================="
