#!/usr/bin/env bash
FILENAME=${1?Error: no filename given}
COMPONENTNAME=${2?Error: no component name given}
echo "==========================================================="
echo "Creating component $FILENAME ..."
echo "==========================================================="
mkdir ./components/$FILENAME
mkdir ./components/$FILENAME/client
mkdir ./components/$FILENAME/server
cp ./private/component-template/component.html.tmpl ./components/$FILENAME/client/$FILENAME.html
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/client/$FILENAME.html
rm ./components/$FILENAME/client/$FILENAME.html.original
sed -i'.original' "s/FILE_NAME_GOES_HERE/$FILENAME/g" ./components/$FILENAME/client/$FILENAME.html
rm ./components/$FILENAME/client/$FILENAME.html.original
cp ./private/component-template/component.js.tmpl ./components/$FILENAME/client/$FILENAME.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/client/$FILENAME.js
rm ./components/$FILENAME/client/$FILENAME.js.original
cp ./private/component-template/component.less.tmpl ./components/$FILENAME/client/$FILENAME.less
sed -i'.original' "s/FILE_NAME_GOES_HERE/$FILENAME/g" ./components/$FILENAME/client/$FILENAME.less
rm ./components/$FILENAME/client/$FILENAME.less.original
cp ./private/component-template/component-publications.js.tmpl ./components/$FILENAME/server/$FILENAME-publications.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/server/$FILENAME-publications.js
rm ./components/$FILENAME/server/$FILENAME-publications.js.original
cp ./private/component-template/component-methods.js.tmpl ./components/$FILENAME/server/$FILENAME-methods.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/server/$FILENAME-methods.js
rm ./components/$FILENAME/server/$FILENAME-methods.js.original
echo "COMPONENT CREATED!"
echo "==========================================================="
