firstNames = [
    'Angus',
    'Griff',
    'Bovi',
    'Axel',
    'Cowen',
    'Dart',
    'Elum',
    'Frack',
    'Goff',
    'Hulk',
    'Ike',
    'Otto',
    'Bo',
    'Achilles',
    'Achillios',
    'Adonis',
    'Aegis',
    'Aesop',
    'Agata',
    'Agnete',
    'Aikaterine',
    'Alekos',
    'Alena',
    'Aleta',
    'Alexandra',
    'Alexios',
    'Altair',
    'Ambrosia',
    'Ander',
    'Apolo',
    'Apollo',
    'Apollonia',
    'Apolonia',
    'Archimedes',
    'Arete',
    'Aristotle',
    'Artemisia',
    'Baruch',
    'Berenice',
    'Chloris',
    'Chrysanthe',
    'Cleopatra',
    'Cletus',
    'Cloris',
    'Costa',
    'Damianos',
    'Demetria',
    'Demetrius',
    'Denys',
    'Dino',
    'Dion',
    'Dionysios',
    'Dorkas',
    'Elias',
    'Erasmus',
    'Eugen',
    'Eunike',
    'Euphemia',
    'Eupraxia',
    'Hagne',
    'Helene',
    'Hero',
    'Hecter',
    'Homer',
    'Icarus',
    'Irene',
    'Isidora',
    'Izador',
    'Kallisto',
    'Kallista',
    'Kassandra',
    'Lysander',
    'Lysistrata',
    'Markos',
    'Nike',
    'Niko',
    'Odysseus',
    'Orphea',
    'Pelagios',
    'Sappho',
    'Syntyche',
    'Thaddaeus',
    'Thais',
    'Theodora',
    'Theodore',
    'Theodoros',
    'Theodosia',
    'Theophania',
    'Theophila',
    'Theophilus',
    'Timon',
    'Thimothea',
    'Thimotheos',
    'Xhanthippe',
    'Xhantos',
    'Xenia',
    'Felix',
    'Flavian',
    'Aranare',
    'Arudara',
    'Asijaka',
    'Bansabira',
    'Didikase',
    'Duripi',
    'Itaja',
    'Jadikira',
    'Ja-Pa-Qa',
    'Kikeru',
    'Kitanetos',
    'Kubaba',
    'Mijararos',
    'Nashuja',
    'Nyx',
    'Pamesijos',
    'Pijaseme',
    'Pijasiros',
    'Pika',
    'Pinaruti',
    'Pitaja',
    'Plato',
    'Pura',
    'Pyka',
    'Rusa',
    'Sima',
    'Sama',
    'Sijapuros',
    'Steffi',
    'Tarina',
    'Titiku',
    'Widina',
    'Yidini',
    'Gregor',
    'Greta',
    'Grete',
    'Griete',
    'Hali',
    'Herakles',
    'Hesper',
    'Hypatia',
    'Hyperia',
    'Hyperion',
    'Isidore',
    'Kali',
    'Kaly',
    'Kyros',
    'Leandros',
    'Leonidas',
    'Leontios',
    'Lukas',
    'Makarios',
    'Maximos',
    'Milos',
    'Moris',
    'Nik',
    'Orion',
    'Paulos',
    'Pericles',
    'Petros',
    'Seraphim',
    'Socrates',
    'Thanos',
    'Thetis',
    'Titos',
    'Zenon',
    'Zeno',
    'Zak',
    'Zacheus',
    'Jak',
    'Kilmus',
    'Bronk',
    'Gronk',
    'Dronk',
    'Gorman',
    'Gark',
    'Gurk',
    'Mork',
    'Nano',
    'Baldy',
    'Papi',
    'Bud',
    'Forg',
    'Kapin',
    'Bobber',
    'Net',
    'Seth',
    'Anubis',
    'Nour',
    'Adom',
    'Rashida',
    'Aat',
    'Ahmes',
    'Amenia',
    'Bebi',
    'Bek',
    'Benerib',
    'Buneb',
    'Kheops',
    'Caesarion',
    'Ded',
    'Didia',
    'Djet',
    'Duatentopet',
    'Dua',
    'Euclid',
    'Erat',
    'Eurydice',
    'Ganymede',
    'Gilukhipa',
    'Hannu',
    'Hakor',
    'Hemaka',
    'Hep',
    'Horus',
    'Huya',
    'Ibi',
    'Lutty',
    'Kop',
    'Kapes',
    'Kashta',
    'Kai',
    'Khay',
    'Khensa',
    'Keti',
    'Kiya',
    'Lysandra',
    'Maatkare',
    'Maya',
    'Yaxi',
    'Mimi',
    'Mek',
    'Menna',
    'Meru',
    'Mihn',
    'Nak',
    'Nauni',
    'Necho',
    'Nefertiti',
    'Nanc',
    'Nuya',
    'Oso',
    'Osorkon',
    'Pacer',
    'Pipi',
    'Qenna',
    'Qen',
    'Raemka',
    'Ramses',
    'Scota',
    'Semat',
    'Seti',
    'Sharek',
    'Sitre',
    'Tabiry',
    'Teta',
    'Tey',
    'Tia',
    'Tiaa',
    'Tiye',
    'Tuya',
    'Tutu',
    'Unas',
    'Yuna',
    'Zannanza'

];


lastNamePrefixes = [
    'Strong',
    'Strong',
    'Strong',
    'Strong',
    'Strong',
    'Proud',
    'Proud',
    'Proud',
    'Proud',
    'Proud',
    'Burl',
    'Tough',
    'Ox',
    'Thunder',
    'Rumble',
    'Puff',
    'High',
    'High',
    'High',
    'High',
    'Long',
    'Gruff',
    'Vile',
    'Low',
    'Gore',
    'Gore',
    'Buff',
    'Hef',
    'Vig',
    'Hard',
    'Stiff',
    'Fierce',
    'Jack',
    'Kal',
    'Hark',
    'Huf',
    'Low',
    'Thick',
    'Ruf',
    'Stout',
    'Dire',
];


lastNameSuffixes = [
    'hoof',
    'snout',
    'horn',
    'withers',
    'muzzle',
    'cannon',
    'hock',
    'ax',
    'bone',
    'foot',
    'udder',
    'buck',
    'husk',
    'chuck',
    'shank',
    'loin',
    'plate',
    'tongue',
    'head',
    'huff',
    'ton',
    'block',
    'dark'
];

positions = [
    'brute',
    'runner',
    'poacher',
    'climber',
    'thrower',
];
getFirstName = function() {

    const index = Math.floor(Math.random() * firstNames.length);
    return firstNames[index];

};

getLastName = function() {

    const prefixIndex = Math.floor(Math.random() * lastNamePrefixes.length);
    const suffixIndex = Math.floor(Math.random() * lastNameSuffixes.length);
    return `${lastNamePrefixes[prefixIndex]}${lastNameSuffixes[suffixIndex]}`;

};

getPosition = function() {

    const index = Math.floor(Math.random() * positions.length);
    return positions[index];

};

generateStat = function({ min, max }) {

    return Math.floor(min + Math.random() * (max - min));

};

if (Players.find().count() === 0) {

    for (let x = 0; x < 1001; x += 1) {

        const player = new Player();
        player.populate({ playerData: Players.random() });
        // console.log(player);
        player.save();

    }

}

if (Managers.find().count() === 0) {

    for (let x = 0; x < 120; x += 1) {

        const manager = new Manager();
        manager.populate({ managerData: Managers.random() });
        manager.save();

    }

}
